apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: yoyota/forward-head-posture-tfrecord
deploy:
  helm:
    releases:
      - name: forward-head-posture-tfrecord
        namespace: yoyota
        chartPath: helm
        setValueTemplates:
          image.repository: "{{.IMAGE_NAME}}"
          image.tag: "{{.DIGEST_HEX}}"
