{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tfrecord.serviceAccountName" . }}
  labels:
{{ include "tfrecord.labels" . | nindent 4 }}
{{- end -}}
